# Generated by Django 4.1.2 on 2022-10-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteitem',
            old_name='Favorite',
            new_name='favorite',
        ),
    ]
